### ISSUE TITLE
Bumping patch adds a second `-beta` to `pyproject.toml`

### ISSUE THREAD

**Issue by Zeitsperre** [callowayproject/bump-my-version#128] opened 2024-01-16 16:55 UTC
* bump-my-version version: 0.15.3
* Python version: Python3.12
* Operating System: Ubuntu LTS 22.04

### Description

I have a CI action that automatically bumps the patch version when changes are seen in the codebase of my project. Last month, this action bumped the patch version in affected files (`0.7.24-beta` → `0.7.25-beta`), but added an extra `-beta` in the version string listed in my `pyproject.toml` (i.e. `0.7.24-beta` → `0.7.25-beta-beta`). This caused further actions to fail.

### What I Did

```
$ bump-my-version bump patch
```

### Additional Information

See: https://github.com/Ouranosinc/xscen/commit/e21e15b999e154fc05eecd1d19c7da938f2b7634
Action run: https://github.com/Ouranosinc/xscen/actions/runs/7267026398/job/19799964307

**Comment by coordt** [comment] 2024-01-17 16:26
I've had difficulty reproducing your error in my test suite. Could you run `bump-my-version bump --dry-run -vv patch` and paste in the result?

**Comment by coordt** [comment] 2024-01-29 14:52
I'm closing this for now, since you haven't responded with more details and I can't reproduce.

Feel free to re-open this with more information.

**Closed by coordt** 2024-01-29 14:52 UTC
Labels: bug

**Comment by Zeitsperre** [comment] 2024-01-29 14:56
Hi, sorry for that, it seems like it happened only once, and I couldn't reproduce it either. I imagine this has been addressed in some way since v0.15.3. Thanks!
