### ISSUE TITLE
Optional "release" part always present vs bump2version

### ISSUE THREAD

**Issue by ndevenish** [callowayproject/bump-my-version#45] opened 2023-08-14 11:24 UTC
* bump-my-version version: 0.9.2
* Python version: 3.11.4
* Operating System: macos

### Description

I'm seeing a difference in behaviour between bump-my-version and bump2version based on our existing configuration. I can't work out what is different about our behaviour. Perhaps the way this was set up initially only worked by luck?

Our release scheme is main which is WIP for next release, and branches for each release (which have released patch versions):
```
 (main)
3.16.dev -> 3.16.0 -> 3.16.1 -> 3.16.2    (v3.16 branch)
   V
3.17.dev -> 3.17.0 -> 3.17.2 -> ...       (v3.17 branch)
```

### What I Did

Our existing `.bumpversion.cfg` (have converted to pyproject and get same behaviour):
```ini
[bumpversion]
current_version = 3.16.dev1
commit = True
tag = False
parse = (?P<major>\d+)\.(?P<minor>\d+)\.(?P<release>[a-z]+)?(?P<patch>\d+)?
serialize =
        {major}.{minor}.{release}{patch}
        {major}.{minor}.{release}
        {major}.{minor}.{patch}

[bumpversion:part:patch]

[bumpversion:part:release]
optional_value = prod
first_value = dev
values =
        dev
        prod
```
Running with `bump-my-version bump release --no-commit && git diff`, the optional part always gets added:
```diff
diff --git a/.bumpversion.cfg b/.bumpversion.cfg
index 2f31645..4878415 100644
--- a/.bumpversion.cfg
+++ b/.bumpversion.cfg
@@ -1,5 +1,5 @@
 [bumpversion]
-current_version = 3.16.dev1
+current_version = 3.16.prod
 commit = True
 tag = False
```
But running with `dump2version release --no-commit && git diff` (b2v=v1.0.1) works as we are used to:

```diff
--- a/.bumpversion.cfg
+++ b/.bumpversion.cfg
@@ -1,5 +1,5 @@
 [bumpversion]
-current_version = 3.16.dev1
+current_version = 3.16.0
 commit = True
```

**Comment by coordt** [comment] 2023-08-16 13:19
I'm surprised by this, and I'm not certain if it is a bug in bump2version or a bug in bump-my-version.

My understanding is that the order was supposed to be top-down (first to last). The first successful serialization is chosen.

I've made a test that reproduces the behavior you're seeing and am trying to figure out what is going on.

**Comment by ndevenish** [comment] 2023-08-16 13:26
> The first successful serialization is chosen.

My understanding from [Version Parts](https://callowayproject.github.io/bump-my-version/reference/version-parts.html) was that it was more "the first successful serialization _without_ default values".

I haven't dug into the code here but could easily see a "naive" loop-until-positive-match-or-no-more-entries choosing the last, while a different algorithm might have the last two grouped together somehow when it realises there are no more entries, choosing the "last examined" entry instead.

**Comment by coordt** [comment] 2023-08-16 13:47
The code for this in bump2version and bump-my-version is practically identical.

If you could run both commands in verbose mode, it will display debugging messages that outline the logic between them.

**Comment by coordt** [comment] 2023-09-05 12:05
Closing due to lack of more information.

**Closed by coordt** 2023-09-05 12:05 UTC

**Comment by ndevenish** [comment] 2023-09-05 12:42
Sorry, I didn't realise you were waiting for information; are you saying that you cannot reproduce this?

The following bash script reproduces the same result I saw above:
```bash
git init
cat <<EOF > .bumpversion.cfg
[bumpversion]
current_version = 3.16.dev1
commit = True
tag = False
parse = (?P<major>\d+)\.(?P<minor>\d+)\.(?P<release>[a-z]+)?(?P<patch>\d+)?
serialize =
        {major}.{minor}.{release}{patch}
        {major}.{minor}.{release}
        {major}.{minor}.{patch}

[bumpversion:part:patch]

[bumpversion:part:release]
optional_value = prod
first_value = dev
values =
        dev
        prod
EOF
git add .bumpversion.cfg
git commit -m "Initial"
bump-my-version bump release --verbose --no-commit && git diff
git reset --hard HEAD
bump2version release --verbose --no-commit && git diff
```
It doesn't seem to be checking the parts at all?
```
+ bump-my-version bump release --verbose --no-commit
Starting BumpVersion 0.10.0
Reading config file .bumpversion.cfg:

WARNING:

The .cfg file format is deprecated. Please use .toml instead.

Parsing version '3.16.dev1' using regexp '(?P<major>\d+)\.(?P<minor>\d+)\.(?P<release>[a-z]+)?(?P<patch>\d+)?'
Parsed the following values: major=3, minor=16, patch=1, release=dev
Attempting to increment part 'release'
Values are now: major=3, minor=16, patch=0, release=prod
New version will be '3.16.prod'
Asserting files  contain the version string...
Writing to config file .bumpversion.cfg:
*** before .bumpversion.cfg
--- after .bumpversion.cfg
```

**Comment by ndevenish** [comment] 2023-09-05 12:45
> If you could run both commands in verbose mode, it will display debugging messages that outline the logic between them.
> 
> Here is what I am seeing from your configuration:

FWIW I read this as "You can generate more information with --verbose, I have done so and got this output"; so didn't read this as asking for more information

**Comment by ndevenish** [comment] 2023-09-05 12:47
In fact, _your exact reproduction_ demonstrates the issue; your reproduction generates "3.16.prod" where bump2version doesn't, so what extra information were you waiting for?

**Comment by ndevenish** [comment] 2023-09-05 12:48
bump2version's verbose output:
```
+ bump2version release --verbose --no-commit
Reading config file .bumpversion.cfg:
[bumpversion]
current_version = 3.16.dev1
commit = True
tag = False
parse = (?P<major>\d+)\.(?P<minor>\d+)\.(?P<release>[a-z]+)?(?P<patch>\d+)?
serialize =
        {major}.{minor}.{release}{patch}
        {major}.{minor}.{release}
        {major}.{minor}.{patch}

[bumpversion:part:patch]

[bumpversion:part:release]
optional_value = prod
first_value = dev
values =
        dev
        prod

Attempting to increment part 'release'
Values are now: major=3, minor=16, patch=0, release=prod
New version will be '3.16.0'
Asserting files  contain the version string...
current_version=3.16.dev1
commit=True
tag=False
parse=(?P<major>\d+)\.(?P<minor>\d+)\.(?P<release>[a-z]+)?(?P<patch>\d+)?
serialize=
{major}.{minor}.{release}{patch}
{major}.{minor}.{release}
{major}.{minor}.{patch}
new_version=3.16.0
Writing to config file .bumpversion.cfg:
[bumpversion]
current_version = 3.16.0
commit = True
tag = False
parse = (?P<major>\d+)\.(?P<minor>\d+)\.(?P<release>[a-z]+)?(?P<patch>\d+)?
serialize =
        {major}.{minor}.{release}{patch}
        {major}.{minor}.{release}
        {major}.{minor}.{patch}

[bumpversion:part:patch]

[bumpversion:part:release]
optional_value = prod
first_value = dev
values =
        dev
        prod


Would prepare Git commit
Would add changes in file '.bumpversion.cfg' to Git
Would commit to Git with message 'Bump version: 3.16.dev1 → 3.16.0'
Would tag 'v3.16.0' with message 'Bump version: 3.16.dev1 → 3.16.0' in Git and not signing
```

**Comment by coordt** [comment] 2023-09-06 11:55
@ndevenish I'm sorry, you are right, I was not very specific. As I mentioned above, the code between bump2version and bump-my-version in this part functions identically. And they work as expected.

The information I was looking for was detailed information about how bump2version gives you a different result.

**Comment by ndevenish** [comment] 2023-09-06 13:02
Hmm, I'm still confused then, you aren't seeing the output different from the two tools?

I noticed that none of my output had any of the
```
Found '{major}.{minor}.{release}{patch}' to be a usable serialization format
Found '{major}.{minor}.{release}' to be a usable serialization format
Found '{major}.{minor}.{patch}' usable serialization format, but it's longer
```
that yours did - is it possible that the bump-my-version `.bumpversion.cfg` handling isn't picking it up?

Otherwise, I'll try to work out where things are diverging when I get a chance, I'd really like to migrate off of bump2version.
